Repository Iraq-WBC-Capstones-2020/we-care-web, pull requests merged in 2020-08, with the labels that each got.

#26 makes test suite pass
  src/App.test.js
Labels: bug

#39 Fixed missing author names
  src/components/For You/Quotes.js
Labels: fix

#51 Feature posting
  package-lock.json
  package.json
  src/App.js
  src/components/For You/ForYou-Posts.js
  src/components/For You/ForYou.js
  src/components/For You/Quotes.js
  src/components/For You/post-textarea.js
  src/components/For You/post.js
  src/components/profile-page/profile-your-posts/post.js
  src/components/profile-page/profile-your-posts/profile-your-posts.js
  src/firebase/firebase.js
  src/redux/actions.js
Labels: feature

#68 Connects survey to chatroom
  src/components/For You/Navbar.js
  src/components/chatroom-page/chatroom-page.js
  src/components/home-page/navbar.js
  src/components/profile-page/navbar.js
  src/components/survey/Navbar.js
  src/components/survey/survey.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/reducer.js
  src/redux/store.js
Labels: enhancement, fix

#73 Journals functionality
  src/components/For You/post.js
  src/components/profile-page/all-journals/all-journals.js
  src/components/profile-page/profile-journal/add-journal.js
  src/components/profile-page/profile-journal/journal.js
  src/components/profile-page/profile-journal/profile-journal.js
  src/components/profile-page/profile-page.js
  src/components/profile-page/profile/right-sidebar.js
  src/firebase/firebase.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/reducer.js
  src/redux/store.js
Labels: feature

#79 Search users & Show their profile
  public/index.html
  public/locales/en/translation.json
  public/locales/tu/translation.json
  src/App.js
  src/components/For You/post.js
  src/components/chatroom-page/chatroom-page.js
  src/components/chatroom-page/user-not-found-page.js
  src/components/profile-page/navbar.js
  src/components/profile-page/profile/about.js
  src/components/profile-page/profile/right-sidebar.js
  src/components/profile-page/search-box.js
  src/components/searched-user-profile/about.js
  src/components/searched-user-profile/right-sidebar.js
  src/components/searched-user-profile/searched-user-profile.js
  src/firebase/firebase.js
  src/redux/actionTypes.js
  src/redux/actions.js
  src/redux/reducers/reducer.js
  src/redux/store.js
Labels: feature
